[workspace]
resolver = "2"
members = ["vnt","common","vnt-cli","vnt-jni"]

[profile.release]
opt-level = 'z'
debug = 0
debug-assertions = false
strip= "debuginfo"
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false
